version: '3'
services:

  polkadot:
    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
      - "127.0.0.1:9615:9615/tcp"
    image: chevdor/polkadot:latest
    volumes:
      - "polkadot-data:/data"
    command: sh -c "polkadot --rpc-external --prometheus-external --log warn --rpc-cors=all"

  vedran:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: start --fee=0.1 --auth-secret=test-secret
    image: nodefactory/vedran:${IMAGE_TAG:-latest}
    container_name: "vedran"
    ports:
      - "${LB_LOCAL_PORT:-4000}:${LB_REMOTE_PORT:-4000}"

  vedran-daemon:
    image: nodefactory/vedran-daemon:${IMAGE_TAG:-v0.1.0}
    depends_on:
      - vedran
      - polkadot
    entrypoint: /bin/sh -c "sleep 5; ./vedran-daemon --id test-id --lb http://vedran:4000 --node-rpc http://polkadot:9933 --node-metrics http://polkadot:9615 --payout-address 0xtestaddress --log-level debug"

volumes:
  polkadot-data:
